import React from 'react';
export default function Navigation({ activeStartDate, drillUp, formatMonthYear, formatYear, locale, maxDate, minDate, navigationAriaLabel, navigationAriaLive, navigationLabel, next2AriaLabel, next2Label, nextAriaLabel, nextLabel, prev2AriaLabel, prev2Label, prevAriaLabel, prevLabel, setActiveStartDate, showDoubleView, view, views, }: {
    activeStartDate: any;
    drillUp: any;
    formatMonthYear?: (locale: any, date: any) => any;
    formatYear?: (locale: any, date: any) => any;
    locale: any;
    maxDate: any;
    minDate: any;
    navigationAriaLabel?: string;
    navigationAriaLive: any;
    navigationLabel: any;
    next2AriaLabel?: string;
    next2Label?: string;
    nextAriaLabel?: string;
    nextLabel?: string;
    prev2AriaLabel?: string;
    prev2Label?: string;
    prevAriaLabel?: string;
    prevLabel?: string;
    setActiveStartDate: any;
    showDoubleView: any;
    view: any;
    views: any;
}): React.ReactElement;
